name: Build & Publish USTBB

on:
  workflow_dispatch:        # allow manual run
  schedule:
    - cron: "0 * * * *"     # runs every hour (UTC)
  push:
    branches: [ main ]      # also run on pushes to main

permissions:
  contents: write           # needed to read repo & (optionally) commit
  pages: write              # needed to publish Pages
  id-token: write           # required by deploy-pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python app.py --query "longevity OR aging OR chronic disease treatment OR randomized trial"

      - name: Ensure .nojekyll exists
        run: |
          mkdir -p output
          touch output/.nojekyll

      - name: Upload artifact (output/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
